export const canvasStyles = {
  background: {
    container: {
      position: 'relative',
      width: '100%',
      height: '100%',
      overflow: 'hidden',
      pointerEvents: 'auto',
    },
    image: {
      position: 'absolute',
      top: '0',
      left: '0',
      width: '100%',
      height: '100%',
      objectFit: 'cover',
      zIndex: 1,
    },
    video: {
      position: 'absolute' as const,
      top: '0',
      left: '0',
      width: '100%',
      height: '100%',
      objectFit: 'cover' as const,
      zIndex: 1,
      transform: 'scaleX(-1)' as const,
    },
    overlay: {
      position: 'absolute' as const,
      inset: 0,
      background:
        'radial-gradient(900px 520px at 15% 15%, rgba(63, 224, 200, 0.12), transparent 60%), radial-gradient(800px 480px at 85% 10%, rgba(248, 180, 88, 0.12), transparent 55%), linear-gradient(180deg, rgba(10, 12, 18, 0.18), rgba(10, 12, 18, 0.42))',
      zIndex: 2,
      pointerEvents: 'none',
    },
  },
  canvas: {
    container: {
      position: 'relative',
      width: '100%',
      height: '100%',
      zIndex: '1',
      pointerEvents: 'auto',
    },
  },
  subtitle: {
    container: {
      backgroundColor: 'transparent',
      padding: '15px 30px',
      borderRadius: '12px',
      minWidth: '60%',
      maxWidth: '95%',
      border: '1px solid',
      borderColor: 'rgba(255, 255, 255, 0.12)',
    },
    imageContainer: {
      position: 'absolute' as const,
      right: '24px',
      top: '50%',
      transform: 'translateY(-50%)',
      display: 'flex',
      flexDirection: 'column',
      gap: '12px',
      maxWidth: '24%',
      maxHeight: '45%',
      zIndex: 10,
    },
    image: {
      width: '100%',
      maxWidth: '100%',
      maxHeight: '28vh',
      height: 'auto',
      objectFit: 'contain' as const,
      borderRadius: '10px',
      border: '1px solid rgba(255, 255, 255, 0.12)',
      boxShadow: '0 12px 26px rgba(0, 0, 0, 0.35)',
      display: 'block',
      backgroundColor: 'rgba(0, 0, 0, 0.12)',
    },
    text: {
      color: 'var(--app-text)',
      fontSize: '1.5rem',
      textAlign: 'center',
      lineHeight: '1.4',
      whiteSpace: 'pre-wrap',
      letterSpacing: '0.01em',
    },
  },
  wsStatus: {
    container: {
      position: 'relative',
      // top: '20px',
      // left: '20px',
      zIndex: 2,
      padding: '8px 16px',
      borderRadius: '20px',
      fontSize: '14px',
      fontWeight: 'medium',
      color: 'var(--app-text)',
      transition: 'all 0.2s',
      cursor: 'pointer',
      userSelect: 'none',
      _hover: {
        opacity: 0.8,
      },
    },
  },
};
